# Generated by Django 5.0.6 on 2024-08-15 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_employees', '0012_alter_award_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='advisorid',
        ),
        migrations.AddField(
            model_name='award',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=40),
        ),
    ]
